#
# - 默认引用.env，用于docker-compose.yml内部的变量引用
#
version: '3.2'

services:
  flask:
    build:
      context: flask/
    image: forester/flask:${__VERSION__}
    container_name: forester-flask
    restart: always
    environment: 
      - MONGODB_USERNAME=${F6R_MONGO_USERNAME}
      - MONGODB_PASSWORD=${F6R_MONGO_PASSWORD}
      - MONGODB_HOST=forester-mongo
      - MONGODB_PORT=27017

    volumes:
      # Notice: set host volume for attachment download
      - ${__DATA_VOLUME_ROOT__}/download:/download
      - ./wait-for-ip.sh:/wait-for-ip.sh:ro

    networks:
      - forester_network
    # 仅用于单机测试
    # ports:
    #   - "8080:8000"

  xunsearch-server:
    image: hightman/xunsearch
    container_name: forester-xunsearch-server
    restart: always

    volumes:
      - ./xunsearch/cmccb2b.ini:/usr/local/xunsearch/sdk/php/app/cmccb2b.ini:ro
      - ${__DATA_VOLUME_ROOT__}/xunsearch:/usr/local/xunsearch/data

    networks:
      - forester_network

  xunsearch:
    build:
      context: xunsearch/
    image: forester/xunsearch:${__VERSION__}
    container_name: forester-xunsearch
    restart: always
    environment: 
      - MONGODB_URI=mongodb://${F6R_MONGO_USERNAME}:${F6R_MONGO_PASSWORD}@forester-mongo:27017

    networks:
      - forester_network
    # 仅用于单机测试
    # ports:
    #   - "9000:80"

    depends_on: 
      - flask
      - xunsearch-server

  proxy:
    image: nginx:1.20.1
    container_name: forester-proxy
    restart: always

    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - forester_network
    # Notes: you can update serveice ports for deployment.
    ports:
      - "8080:80"
    
    depends_on: 
      - xunsearch
      - flask

  cronjobs:
    build:
      context: cronjobs/
    image: forster/cronjobs:${__VERSION__}
    container_name: forester-cronjobs
    restart: always

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./wait-for-ip.sh:/wait-for-ip.sh:ro

    networks:
      - forester_network

    depends_on: 
      - xunsearch
      - flask
    # command: ["/bin/sh", "/wait-for-ip.sh", "forester-flask:8000", "--", "crond", "-f", "-d", "6", "-c", "/etc/crontabs"]

  mongo:
    image: mongo:3.6
    container_name: forester-mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${F6R_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${F6R_MONGO_PASSWORD}

    volumes:
      # Notice: set host volume for mongo db
      - ${__DATA_VOLUME_ROOT__}/db:/data/db

    networks:
      - forester_network
    # 仅用于单机开发和测试
    # ports: 
    #   - "47017:27017"
  
networks:
  forester_network:
    external: false
    attachable: true