version: '3'

services:
  # flask:
  #   build:
  #     context: flask/
  #   image: forester/flask
  #   container_name: forester-flask
  #   restart: always

  #   networks:
  #     - forester_net
  #   ports: 
  #     - 8080:80

  #   volumes:
  #     # Notice: set host volume for attachment download
  #     - ../../cmdata/download:/download

  #   environment:
  #     - FLASK_APP=app/main.py
  #     - FLASK_DEBUG=1
  #     - 'RUN=flask run --host=0.0.0.0 --port=80'

  scrapy:
    build:
      context: scrapy/
    image: forester/scrapy
    container_name: forester-scrapy
    restart: always

    networks:
      - forester_net
    ports: 
      - 6800:6800

    volumes:
      # Notice: set host volume for attachment download
      - ../../cmdata/download:/download

  mongo:
    image: mongo:3.6
    container_name: forester-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: forester
      # MONGO_INITDB_DATABASE: cmccb2b

    networks:
      - forester_net
    ports:
      - 27017:27017

    volumes:
      # Notice: set host volume for mongo db
      - ../../cmdata/db:/data/db

    # depends_on: 
    #   - forester-log
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://127.0.0.1:8514"
    #     tags: 'mongo'

networks:
  forester_net:
    external: false
    # attachable: true